import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

interface AlertEmailProps {
    to: string;
    subject: string;
    markdown: string;
}

export const sendAlertEmail = async ({ to, subject, markdown }: AlertEmailProps) => {
    if (!process.env.RESEND_API_KEY) {
        console.warn('⚠️ RESEND_API_KEY not set. Email not sent.');
        return { success: false, error: 'Missing API Key' };
    }

    try {
        const { data, error } = await resend.emails.send({
            from: 'Titan Neural Link <onboarding@resend.dev>', // Default testing domain
            to: [to],
            subject: `[TITAN ALERT] ${subject}`,
            html: `
            <div style="font-family: sans-serif; background: #000; color: #fff; padding: 20px; border-radius: 8px;">
                <h2 style="color: #ff4444; border-bottom: 1px solid #333; padding-bottom: 10px;">${subject}</h2>
                <div style="font-size: 16px; line-height: 1.6; color: #ccc;">
                    ${markdown.replace(/\n/g, '<br/>')}
                </div>
                <div style="margin-top: 20px; font-size: 12px; color: #666; border-top: 1px solid #333; padding-top: 10px;">
                    Generated by Titan Neural Link v3.4.7
                </div>
            </div>
            `
        });

        if (error) {
            console.error('Resend Error:', error);
            return { success: false, error };
        }

        return { success: true, data };
    } catch (e) {
        console.error('Email Exception:', e);
        return { success: false, error: e };
    }
};
